### ISSUE TITLE
Simple, Lightweight Setup for a Beginner?

### ISSUE THREAD

**Issue by burgers4me** [net4people/bbs#414]
Hi everyone,
I'm in IRN, trying to set up a low-end VPS (only 512 MB of RAM and preferably only with IPv6 as the costs gets lower) with a clean, lightweight configuration, but the learning curve is steep. There are all these protocols and programs like QUIC, gRPC, ws, XTLS, V2ray, xray, xcore, sing-box, etc., and honestly, it’s overwhelming—takes a lot of time just to understand the basics.

I used to run a Hysteria2 connection with minimal configuration, and it worked great, but now it just won’t connect on my home ISP. So I’m currently using trojan(tcp)+tls through vaxilu/x-ui, but the connection feels throttled. Data only arrives in bursts, and it’s frustrating.

Here's the Hysteria2 config I used:
<details>

<summary>Server config (click to open):</summary>

```
listen: :1020

tls:
  cert: /etc/letsencrypt/live/my.website/fullchain.pem
  key: /etc/letsencrypt/live/my.website/privkey.pem

auth:
  type: password
  password: ***

masquerade:
  type: proxy
  proxy:
    url: https://some.website
    rewriteHost: true
```

</details>
<details>

<summary>Client config (click to open):</summary>

```
server: my.website:1020

auth: ***

bandwidth:
  up: 20 mbps
  down: 100 mbps

socks5:
  listen: 127.0.0.1:1080

http:
  listen: 127.0.0.1:8080
```

</details>

I’m not even sure if there’s a way to get around whatever’s blocking my Hysteria2 connection, and I don’t know what protocol would work best with my ISP. Does anyone know of a tool or method to test different protocols/configs to see what would connect best? Like a benchmarking tool?

I’d really rather use original project repositories or minimalist tools, instead of all these forks and scripts that bundle everything together and aren’t easy to trust or check for security issues. I liked Hysteria2 because it was straightforward, lightweight, and easy to set up. 

Any ideas?
